AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'

Documentation:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 500

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/ClassAndModuleChildren:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: aligned

Style/AndOr:
  EnforcedStyle: conditionals
